title: "BFMAP by Jicai Jiang"
description: "Bayesian Fine-Mapping and Aassociation for Population and Pedigree Data"
title2: "Bayesian Fine-Mapping and Aassociation for Population and Pedigree Data"

